version: '3.8'

services:
  # Frontend - React with Next.js
  callsense-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - callsense-backend

  # Backend - Node.js with Express
  callsense-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/callsense
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secure-jwt-secret-key-here
      - ELEVENLABS_API_KEY=your-elevenlabs-api-key
      - GEMINI_API_KEY=your-gemini-api-key
      - MAX_FILE_SIZE=50MB
      - ALLOWED_AUDIO_TYPES=mp3,wav,m4a,aac
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis

  # Database - MongoDB
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=callsense
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  # Cache - Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Reverse Proxy - Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - callsense-frontend
      - callsense-backend

volumes:
  mongodb_data:
  redis_data: